#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

# Complete the acmTeam function below.
def acmTeam(topic):
    lst = []
    for i in range(0,len(topic)):
        for j in range(i+1,len(topic)):
            res = 0
            for k in range(0,len(topic[i])):
                if topic[i][k]=='1' or topic[j][k]=='1':
                    res += 1
            lst.append(res)
    maxi = 0
    count = 0
    for i in lst:
        if i>maxi:
            count = 1
            maxi = i
        elif i==maxi:
            count += 1
    res = [maxi,count]
    return res
            


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    topic = []

    for _ in range(n):
        topic_item = input()
        topic.append(topic_item)

    result = acmTeam(topic)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
