#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the beautifulBinaryString function below.
def beautifulBinaryString(b):
    res = 0
    b = list(b)
    for i in range(0,len(b)-2):
        if b[i]=='0':
            if b[i+1]=='1':
                if b[i+2]=='0':
                    b[i+2] = '1'
                    res+=1
    return res


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    b = input()

    result = beautifulBinaryString(b)

    fptr.write(str(result) + '\n')

    fptr.close()
