#!/bin/python3

import math
import os
import random
import re
import sys

def sumdig(n):
    s = 0
    while n>0:
        s = s+n%10
        n //= 10
    return s

if __name__ == '__main__':
    n = int(input())
    maxsum = 0
    maxdiv=1
    for i in range(2,n+1):
        if n%i == 0:
            temp = sumdig(i)
            if temp > maxsum:
                maxsum = temp
                maxdiv = i
    print(maxdiv)
            

