#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the closestNumbers function below.
def closestNumbers(arr):
    arr.sort()
    mini = 100000000
    n = len(arr)
    for i in range(0,len(arr)-1):
        if arr[i+1]-arr[i] < mini:
            mini = arr[i+1]-arr[i]
    lst = []
    for i in range(0,n-1):
        if arr[i+1]-arr[i] == mini:
            lst.append(arr[i])
            lst.append(arr[i+1])
    return lst

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = closestNumbers(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
