#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the stepPerms function below.
def stepPerms(n):
    if n==1:
        return 1
    if n==2:
        return 2
    if n==3:
        return 4
    lst = [1,2,4]
    for i in range(3,n):
        lst.append(lst[i-1]+lst[i-2] + lst[i-3])
    return lst[n-1]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = int(input())

    for s_itr in range(s):
        n = int(input())

        res = stepPerms(n)

        fptr.write(str(res) + '\n')

    fptr.close()
