#!/bin/python3

import os
import sys

# Complete the solve function below.
def solve(arr, queries):
    lst = []
    for i in queries:
        if(i[0]<len(arr) and arr[i[0]]==0 and i[0]!=i[1]):
            lst.append('Odd')
        elif i[0] > i[1] :
            lst.append("Odd")
        elif arr[i[0]-1]%2 == 0:
            
                lst.append("Even")
            
        else:
            lst.append("Odd")
    return lst


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr_count = int(input())

    arr = list(map(int, input().rstrip().split()))

    q = int(input())

    queries = []

    for _ in range(q):
        queries.append(list(map(int, input().rstrip().split())))

    result = solve(arr, queries)

    fptr.write('\n'.join(result))
    fptr.write('\n')

    fptr.close()
