#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the fairRations function below.
def fairRations(B):
    res = 0
    for i in range(0,len(B)):
        if B[i]%2==1 and i==len(B)-1:
            return "NO"
        elif B[i]%2==1 and i==len(B)-2 and B[i]%2==0:
            return "NO"
        elif B[i]%2==1:
            B[i] += 1
            B[i+1] += 1
            res += 2
    return res

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    N = int(input())

    B = list(map(int, input().rstrip().split()))

    result = fairRations(B)

    fptr.write(str(result) + '\n')

    fptr.close()
