#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the gameOfThrones function below.
def gameOfThrones(s):
    lst = [0]*26
    for i in s:
        lst[ord(i)-97] += 1
    even = 0
    odd = 0
    for i in lst:
        if i%2==0:
            even +=1
        else:
            odd +=1
    if len(s)%2==0 and odd==0:
        return "YES"
    elif len(s)%2==1 and odd==1:
        return "YES"
    else:
        return "NO"


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = gameOfThrones(s)

    fptr.write(result + '\n')

    fptr.close()
