#!/bin/python3

import os
import sys

#
# Complete the halloweenParty function below.
#
def halloweenParty(k):
    #
    # Write your code here.
    #
    if k%2 == 0:
        return (k//2)**2
    else:
        return (k//2)*(k//2+1)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        k = int(input())

        result = halloweenParty(k)

        fptr.write(str(result) + '\n')

    fptr.close()
