#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the insertionSort2 function below.
def insertionSort2(arr,i):
    # new = sorted()
    new = sorted(arr[:i+1]) + arr[i+1:]
    return ' '.join(str(k) for k in new)

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))
    for i in range(1,n):
        print(insertionSort2(arr, i))
