#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the luckBalance function below.
def luckBalance(k, contests):
    imp = []
    luck = 0
    for i,j in contests:
        if j==0:
            luck += i
            print(luck)
        else:
            imp.append(i)
    imp.sort(reverse = True)
    for i in imp:
        print(i)
    if k>=len(imp):
        k = len(imp)
    for i in range(0,k):
        luck += imp[i]
    for i in range(k,len(imp)):
        luck -= imp[i]
    return luck

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    contests = []

    for _ in range(n):
        contests.append(list(map(int, input().rstrip().split())))

    result = luckBalance(k, contests)

    fptr.write(str(result) + '\n')

    fptr.close()
