#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the makingAnagrams function below.
def makingAnagrams(s1, s2):
    lst1 = [0]*26
    for i in s1:
        lst1[ord(i)-97] += 1
    lst2 = [0]*26
    for i in s2:
        lst2[ord(i)-97] += 1
    res = 0
    for i in range(0,26):
        res += abs(lst1[i]-lst2[i])
    return res

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s1 = input()

    s2 = input()

    result = makingAnagrams(s1, s2)

    fptr.write(str(result) + '\n')

    fptr.close()
