#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumDistances function below.
def minimumDistances(a):
    mind = 10000
    for i in range(0,len(a)):
        for j in range(i+1,len(a)):
            if a[i]==a[j] and j-i<mind:
                mind = j-i
                break
                
    if mind==10000:
        return -1
    return mind

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    a = list(map(int, input().rstrip().split()))

    result = minimumDistances(a)

    fptr.write(str(result) + '\n')

    fptr.close()
