#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the repeatedString function below.
def repeatedString(s, n):
    res = 0
    for i in s:
        if i=='a':
            res +=1
    mult = n//len(s)
    rem = n%len(s)
    res = res*mult
    for i in range(0,rem):
        if s[i] == 'a':
            res += 1
    return res

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
