#!/bin/python3

import os
import sys
import math
#
# Complete the divisors function below.
#
def divisors(n):
    #
    # Write your code here.
    #
    lst= []
    for i in range(2,int(math.sqrt(n))+1):
        if(n%i == 0):
            lst.append(i)
            if i!=n//i:
                lst.append(n//i)
        
    res = 0
    for i in lst:
        if i%2 == 0:
            res += 1
    # print(set(lst))
    # for i in set(lst):
    #     if i%2 == 0:
    #         res+=1
    # if(n%2 == 0):
    #     res = res+1
    if n%2 == 0:
        return res+1
    return res
    


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        result = divisors(n)

        fptr.write(str(result) + '\n')

    fptr.close()
