#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the isValid function below.
def isValid(s):
    lst = [0]*26
    for i in s:
        lst[ord(i)-97] += 1
    lst.sort(reverse = True)
    if lst[0] == lst[1]+1 and lst[1]!=0:
        lst[0] -= 1
    else:
        j=0
        while j<26 and lst[j]!=1:
            j += 1
        if j!=26:
            lst[j] -= 1
    d = lst[0] - lst[1]
    for i in range(0,len(lst)-1):
        if lst[i]-lst[i+1] != d and lst[i+1]!=0:
            return "NO"
    return "YES"


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = isValid(s)

    fptr.write(result + '\n')

    fptr.close()
