#!/bin/python3

import os
import sys

# Complete the solve function below.
def solve(n,lst):
    
    for i in range(1,8500):
        if lst[i]%n == 0:
            return str(lst[i])

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    lst = [-1,9]
    for i in range(2,8500):
        if i%2==0:
            lst.append(lst[i//2]*10)
        else:
            lst.append(lst[i//2]*10+9)

    for t_itr in range(t):
        n = int(input())

        result = solve(n,lst)

        fptr.write(result + '\n')

    fptr.close()
